### ISSUE TITLE
this does not work properly for GQA case (llama or gemma)

### ISSUE THREAD

**Issue by bzantium** [apple/ml-hypercloning#1]
when expanding the number of query heads for GQA architecture, it needs to clone vectors interleaving way not just repeating.

**Comment by MohammadSamragh** [comment]
Could you please provide example `Llama` and `Gemma` variants where this issue happens? We tested the code for `llama2-7B` and `Gemma-2B` before releasing the code.

**Comment by bzantium** [comment]
`llama2-7b` and `gemma-2b` all use multi-head attention not group query attention but llama3 or gemma2 use GQA which is de facto standard nowadays. I tried it with `llama3-8b` but it does not work properly.

**Comment by MohammadSamragh** [comment]
Thanks for your comment. This has been resolved in the latest commit.
